<a href="https://colab.research.google.com/github/AsmaaAlghamd1/Asmaa_INFO5731_-Spring2021/blob/main/Alghamdi_class_exercise_08(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **The eighth in-class-exercise (20 points in total, 3/30/2021)**

The data for this exercise is from the dataset you created from assignment three. Please perform answer the following questions based on your data:

## (1) (10 points) Write a python program to extract the sentiment related terms from the corpus. You may use python package such as polyglot or external lexicon resources in the question. Rank the sentiment related terms by frequency.

In [1]:

!pip install polyglot
!pip install pyicu
!pip install pycld2
!pip install morfessor
import nltk
nltk.download('stopwords')

Collecting polyglot
  Downloading https://files.pythonhosted.org/packages/e7/98/e24e2489114c5112b083714277204d92d372f5bbe00d5507acf40370edb9/polyglot-16.7.4.tar.gz (126kB)
     |████████████████████████████████| 133kB 11.0MB/s
Building wheels for collected packages: polyglot
  Building wheel for polyglot (setup.py) ... done
  Created wheel for polyglot: filename=polyglot-16.7.4-py2.py3-none-any.whl size=52557 sha256=b8127e71fcd2bdbe27bc2ab5c69900b6cb0a496d3783bf009a57470b57e70b30
  Stored in directory: /root/.cache/pip/wheels/5e/91/ef/f1369fdc1203b0a9347d4b24f149b83a305f39ab047986d9da
Successfully built polyglot
Installing collected packages: polyglot
Successfully installed polyglot-16.7.4
Collecting pyicu
  Downloading https://files.pythonhosted.org/packages/31/46/fa08c8efae2951e67681ec24319f789fc1a74e2096dd74373e34c79319de/PyICU-2.6.tar.gz (233kB)
     |████████████████████████████████| 235kB 13.4MB/s
Building wheels for collected packages: pyicu
  Building wheel for pyicu (setup.py) ... done
  Created wheel for pyicu: filename=PyICU-2.6-cp37-cp37m-linux_x86_64.whl size=1306400 sha256=e7b8f0c2dc6a3b58b9f5c55157dd387e4bd79fea208553330bc83fafcc5d6e7d
  Stored in directory: /root/.cache/pip/wheels/31/21/2f/1c91831e8a93537ab21f6b4b935781b681104635fdb0315791
Successfully built pyicu
Installing collected packages: pyicu
Successfully installed pyicu-2.6
Collecting pycld2
  Downloading https://files.pythonhosted.org/packages/21/d2/8b0def84a53c88d0eb27c67b05269fbd16ad68df8c78849e7b5d65e6aec3/pycld2-0.41.tar.gz (41.4MB)
     |████████████████████████████████| 41.4MB 102kB/s
Building wheels for collected packages: pycld2
  Building wheel for pycld2 (setup.py) ... done
  Created wheel for pycld2: filename=pycld2-0.41-cp37-cp37m-linux_x86_64.whl size=9834259 sha256=d6fb74ab5cc37d17a3c8d573b2809c5d355a057272e25b6684c4e980d436f046
  Stored in directory: /root/.cache/pip/wheels/c6/8f/e9/08a1a8932a490175bd140206cd86a3dbcfc70498100de11079
Successfully built pycld2
Installing collected packages: pycld2
Successfully installed pycld2-0.41
Collecting morfessor
  Downloading https://files.pythonhosted.org/packages/39/e6/7afea30be2ee4d29ce9de0fa53acbb033163615f849515c0b1956ad074ee/Morfessor-2.0.6-py3-none-any.whl
Installing collected packages: morfessor
Successfully installed morfessor-2.0.6
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [2]:
import pandas as pd

d = pd.read_csv('https://raw.githubusercontent.com/AsmaaAlghamd1/Asmaa_INFO5731_-Spring2021/main/List_Tweets%20(22).csv')
d = d.loc[:, ~d.columns.str.contains('^Unnamed')]

In [3]:

%%bash
polyglot download sentiment2.en

[polyglot_data] Downloading package sentiment2.en to
[polyglot_data]     /root/polyglot_data...

In [4]:
from nltk.corpus import stopwords
from textblob import TextBlob


d['Tweets'] = d['Tweets'].str.replace('\d+', '')
d['Tweets'] = d['Tweets'].str.replace('[^\w\s]','')
d['Tweets'] = d['Tweets'].apply(lambda x: " ".join(x.lower() for x in x.split()))
d['Tweets'] = d['Tweets'].str.replace('[^\w\s]','')
stop = stopwords.words('english')
d['Tweets'] = d['Tweets'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))
d

                                                Tweets Sentimental Analysis
0    bya girl got stabbednncovidvaccine johnsonandj...             Natural
1    beveryone read covid herdimmunity covidvaccine...             Natural
2    bgot dose johnsonandjohnson covidvaccine today...             Natural
3    bthis morning trained medical physician studen...             Natural
4    bhypocrisy hypocrisies facebook censors mark z...            Negative
..                                                 ...                  ...
99   bvaccine done case youre curious confirmed doc...             Natural
100  bend day st covid vaccine arm pain slight most...             Natural
101  bicymithisxfxfxxxfxfxfxbb covid still raging c...             Natural
102  bfeeling great pfizer dose one yesterday tiny ...             Natural
103  bis anyone montreal collecting outcomes data p...             Natural

[104 rows x 2 columns]

In [ ]:
from polyglot.text import Text 
d['Tweets'] = d['Tweets'].apply(lambda x: str(TextBlob(x).correct()))

In [10]:
from collections import Counter
freq = Counter(sent_words)
Ranky = pd.DataFrame(list(freq.most_common()), columns=['Words', 'Frequency'])
Ranky.index = list(range(1, len(freq.most_common())+1))
Ranky

          Words  Frequency
1         first          5
2         great          5
3          good          3
4        normal          3
5         happy          3
6          aged          2
7         older          2
8           far          2
9     brilliant          2
10    available          2
11    extremely          1
12  interesting          1
13          ill          1
14    confusing          1
15    difficult          1
16         loud          1
17         poor          1
18       better          1
19      leftist          1
20          lol          1
21        alive          1
22     absolute          1
23        spent          1
24         free          1
25         fake          1
26        right          1
27    wonderful          1
28      average          1
29      success          1
30         half          1
31     everyday          1
32   unexpected          1
33          wow          1
34         mean          1
35         live          1
36        grief          1
37         near          1
38       closed          1
39       higher          1
40         able          1
41         best          1
42       highly          1
43      excited          1
44       latest          1
45    fantastic          1
46        idiot          1
47   previously          1
48      greater          1
49         fuck          1
50         less          1
51      special          1
52      curious          1
53    confirmed          1
54       slight          1
55       mostly          1

In [8]:
from textblob import TextBlob
words = []
sent_words = []
for i in d['Tweets']:
  words.append(i.split(' '))
for i in words:
  for j in i:
    if TextBlob(j).sentiment.polarity != 0:
      sent_words.append(j)
print(sent_words)

['aged', 'older', 'aged', 'older', 'first', 'first', 'extremely', 'interesting', 'ill', 'great', 'far', 'brilliant', 'confusing', 'difficult', 'loud', 'poor', 'better', 'leftist', 'lol', 'alive', 'absolute', 'great', 'spent', 'free', 'fake', 'good', 'right', 'wonderful', 'average', 'success', 'first', 'half', 'far', 'everyday', 'normal', 'brilliant', 'unexpected', 'wow', 'good', 'available', 'first', 'happy', 'mean', 'happy', 'great', 'live', 'good', 'grief', 'happy', 'near', 'closed', 'higher', 'available', 'able', 'best', 'normal', 'highly', 'excited', 'latest', 'fantastic', 'idiot', 'previously', 'greater', 'fuck', 'normal', 'less', 'special', 'curious', 'confirmed', 'slight', 'mostly', 'great', 'first', 'great']

In [9]:
from collections import Counter
import numpy as np
word_count = Counter(sent_words)
words_frame = pd.DataFrame(list(zip(list (word_count.keys()),list (word_count.values()))), columns = ['words', 'Frequency'])
words_frame = words_frame.sort_values(by=['Frequency'], ascending=False)
words_frame.insert( 0,"Rank", np.arange(1,len(words_frame)+1), True)
words_frame

    Rank        words  Frequency
2      1        first          5
6      2        great          5
32     3        happy          3
28     4       normal          3
21     5         good          3
8      6    brilliant          2
1      7        older          2
31     8    available          2
0      9         aged          2
7     10          far          2
50    11      special          1
51    12      curious          1
33    13         mean          1
53    14       slight          1
52    15    confirmed          1
34    16         live          1
35    17        grief          1
36    18         near          1
37    19       closed          1
38    20       higher          1
39    21         able          1
49    22         less          1
40    23         best          1
41    24       highly          1
42    25      excited          1
43    26       latest          1
45    27        idiot          1
46    28   previously          1
47    29      greater          1
48    30         fuck          1
44    31    fantastic          1
27    32     everyday          1
30    33          wow          1
15    34          lol          1
3     35    extremely          1
4     36  interesting          1
5     37          ill          1
9     38    confusing          1
10    39    difficult          1
11    40         loud          1
12    41         poor          1
13    42       better          1
14    43      leftist          1
16    44        alive          1
29    45   unexpected          1
17    46     absolute          1
18    47        spent          1
19    48         free          1
20    49         fake          1
22    50        right          1
23    51    wonderful          1
24    52      average          1
25    53      success          1
26    54         half          1
54    55       mostly          1

In [18]:
Original_positive = 0
Original_negative = 0
Original_neutral = 0
for i in d['Sentimental Analysis']:
  if i == 'Positive':
    Original_positive += 1
  elif i == 'Negative':
    Original_negative += 1
  elif i == 'Natural':
    Original_neutral += 1
print('Original Positive = ', Original_positive)
print('Original Negative = ', Original_negative)
print('Original Neutral = ', Original_neutral)

Original Positive =  0
Original Negative =  0
Original Neutral =  2

## (2) (10 points) Compare the performance of the following tools in sentiment identification: TextBlob (https://textblob.readthedocs.io/en/dev/), VADER (https://github.com/cjhutto/vaderSentiment), TFIDF-based Support Vector Machine (SVM) (Split your data into training and testing data). Take your own annotation as the standard answers. 

Reference code: https://towardsdatascience.com/fine-grained-sentiment-analysis-in-python-part-1-2697bb111ed4

## TextBlob

In [65]:


def perform(i):
  sentiment1 = 0
  if i == 'Positive':
    sentiment1 = 1
  elif i == 'Negative':
    sentiment1 = 2
  return sentiment1


Actual_sent = []
for i in d['Sentimental Analysis']:
  Actual_sent.append(perform(i))

from textblob import TextBlob
sentiment2 = []
for sen in d['Sentimental Analysis']:
  p = TextBlob(sen).sentiment.polarity
  if p > 0:
    sentiment2.append(1)
  elif p < 0:
    sentiment2.append(2)
  elif p == 0.0:
    sentiment2.append(0)
Data1 = pd.DataFrame(list(zip(d['Sentimental Analysis'], Actual_sent,sentiment2)), columns = ['Tweets', 'Actual', 'Predicted'])
Data1

        Tweets  Actual  Predicted
0     Natural        0          1
1     Natural        0          1
2     Natural        0          1
3     Natural        0          1
4    Negative        0          2
..         ...     ...        ...
99    Natural        0          1
100   Natural        0          1
101   Natural        0          1
102   Natural        0          1
103   Natural        0          1

[104 rows x 3 columns]

In [21]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from textblob import TextBlob
nltk.download('vader_lexicon')
positive = 0;negative = 0;neutral = 0
SentAnalyzer = SentimentIntensityAnalyzer()
for i in d['Tweets']:
  sent = TextBlob(i)
  if SentAnalyzer.polarity_scores(i)['compound'] > 0:
    positive += 1
  elif SentAnalyzer.polarity_scores(i)['compound'] < 0:
    negative += 1
  elif SentAnalyzer.polarity_scores(i)['compound'] == 0:
    neutral += 1
print("Positive = ", positive)
print("Negative = ", negative)
print("Neutral = ", neutral)

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!
Positive =  32
Negative =  18
Neutral =  54

In [50]:

from sklearn.metrics import f1_score, accuracy_score
Acc_textblob = accuracy_score(Data1['Actual'], Data1['Predicted'])*100
Scor_textblob = f1_score(Data1['Actual'], Data1['Predicted'], average = 'macro')
print("Text Blob Accuracy is {0}\nF1 Score is {1}".format(Acc_textblob, Scor_textblob ))

Text Blob Accuracy is 0.0
F1 Score is 0.0

In [63]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import classification_report
Vector= TfidfVectorizer(min_df = 5,
                             max_df = 0.8,
                             sublinear_tf = True,
                             use_idf = True)

In [64]:

train_x, test_x, train_y, test_y= train_test_split(d['Tweets'],d['Sentimental Analysis'],test_size=0.33)
train = Vector.fit_transform(train_x_data)
test = Vector.transform(test_x)
svm_model = svm.SVC(kernel='linear')
svm_model.fit(train, train_y)
Predict = svm_model.predict(test)
Result1 = classification_report(test_y, Predict, output_dict=True)
Result1

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

{'Natural': {'f1-score': 0.0, 'precision': 0.0, 'recall': 0.0, 'support': 1},
 'Natural ': {'f1-score': 0.627450980392157,
  'precision': 0.47058823529411764,
  'recall': 0.9411764705882353,
  'support': 17},
 'Negative ': {'f1-score': 0.0, 'precision': 0.0, 'recall': 0.0, 'support': 7},
 'Positive ': {'f1-score': 0.0,
  'precision': 0.0,
  'recall': 0.0,
  'support': 10},
 'accuracy': 0.45714285714285713,
 'macro avg': {'f1-score': 0.15686274509803924,
  'precision': 0.11764705882352941,
  'recall': 0.23529411764705882,
  'support': 35},
 'weighted avg': {'f1-score': 0.3047619047619048,
  'precision': 0.22857142857142856,
  'recall': 0.45714285714285713,
  'support': 35}}

### VADER

In [58]:
import nltk
nltk.download('vader_lexicon')

from nltk.sentiment.vader import SentimentIntensityAnalyzer
vader = SentimentIntensityAnalyzer()
listy = []
for line in d['Tweets']:
  polarity = vader.polarity_scores(line)['compound']
  if polarity > 0:
    listy.append(1)
  elif polarity < 0:
    listy.append(2)
  elif polarity == 0.0:
    listy.append(0)
Show1 = pd.DataFrame(list(zip(d['Tweets'], Actual_sent,  listy)), columns = ['Tweets', 'Actual', 'Predicted'])
Show1

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

                                                Tweets  Actual  Predicted
0    bya girl got stabbednncovidvaccine johnsonandj...       0          0
1    beveryone read covid herdimmunity covidvaccine...       0          0
2    bgot dose johnsonandjohnson covidvaccine today...       0          1
3    bthis morning trained medical physician studen...       0          0
4    bhypocrisy hypocrisies facebook censors mark z...       0          2
..                                                 ...     ...        ...
99   bvaccine done case youre curious confirmed doc...       0          1
100  bend day st covid vaccine arm pain slight most...       0          2
101  bicymithisxfxfxxxfxfxfxbb covid still raging c...       0          1
102  bfeeling great pfizer dose one yesterday tiny ...       0          1
103  bis anyone montreal collecting outcomes data p...       0          2

[104 rows x 3 columns]

In [61]:
from sklearn.metrics import f1_score, accuracy_score
Accuracy = accuracy_score(Show1['Actual'], Show1['Predicted'])*100
Scoree = f1_score(Show1['Actual'],Show1['Predicted'], average = 'macro')
print("Vader Accuracy is {0}\nF1 Score is {1}".format(Accuracy, Scoree))

Vader Accuracy is 51.92307692307693
F1 Score is 0.2278481012658228

In [62]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
nltk.download('vader_lexicon')
positive = 0
negative = 0
neutral = 0
sentimental_analyzer = SentimentIntensityAnalyzer()
for i in d['Tweets']:
  sent = TextBlob(i)
  if sentimental_analyzer.polarity_scores(i)['compound'] > 0:
    positive += 1
  elif sentimental_analyzer.polarity_scores(i)['compound'] < 0:
    negative += 1
  elif sentimental_analyzer.polarity_scores(i)['compound'] == 0:
    neutral += 1
print("Positive = ", positive)
print("Negative = ", negative)
print("Neutral = ", neutral)

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!
Positive =  32
Negative =  18
Neutral =  54